# default config property to run the plugin
config:
 lang: 'en'
 slot: 2 # sets the position of block in player's inventory to use the plugin
 title: "Super Admin Tools" # name of the block
 description: "Test" # description of block
