main: me.d3li0n.AdminTools.Main
name: AdminTools
version: '0.0.3'
author: d3li0n
api-version: 1.16
description: Pack of useful admin commands to control your server. Have fun!

commands:
 Clearchat:
  usage: /<command>
  description: Clears the server chat for all players online.
  permissions: admintools.clearchat
 Slowchat:
  usage: /<command>
  description: Slows the messages sended to chat.
  permissions: admintools.slowchat
 Cc:
  usage: /<command>
  description: Clears the server chat for all players online.
  permissions: admintools.clearchat
 Mutechat:
  usage: /<command>
  description: Mutes the chat for all players who donot have permissions to bypass the restrictions.
  permissions: admintools.mutechat
 Ap:
  usage: /<command>
  description: Opens the interface for managing the plugin and server.
  permissions: admintools.gui
 Ban:
  usage: /<command>
  description: Bans a player forever.
  permissions: admintools.ban
 Unban:
  usage: /<command>
  description: Unbans a player.
  permissions: admintools.unban
 Admins:
  usage: /<command>
  description: Display all admins online.
  permissions: admintools.admins
 Kick:
  usage: /<command>
  description: Kicks a player from server.
  permissions: admintools.kick
 Report:
  usage: /<command>
  description: Report a player for breaking the rules.
  permissions: admintools.report.use
 Mute:
  usage: /<command>
  description: Mutes a player for certain period of time.
  permissions: admintools.mute
 Unmute:
  usage: /<command>
  description: Unmutes player.
  permissions: admintools.unmute
